"""Read and merge key/value updates into a .env file without dropping unrelated keys."""

from __future__ import annotations

import re
from pathlib import Path

_ENV_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def mask_secret(value: str, visible: int = 4) -> str:
    """Return a masked representation for confirmations."""
    if not value:
        return "(empty)"
    if len(value) <= visible:
        return "*" * len(value)
    return value[:visible] + "…" + ("*" * min(8, len(value) - visible))


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse ``KEY=value`` lines; ignore comments and blanks."""
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = _ENV_LINE.match(stripped)
        if m:
            key, raw = m.group(1), m.group(2)
            out[key] = raw.strip().strip('"').strip("'")
    return out


def format_env_value(value: str) -> str:
    """Quote values that need escaping for .env files."""
    if not value:
        return ""
    if any(c in value for c in " #\t\n\"'"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def merge_env_file(
    path: Path,
    updates: dict[str, str | None],
    *,
    create: bool = True,
) -> None:
    """Apply *updates* to *path*; ``None`` removes a key. Preserves other lines/order."""
    existing_lines: list[str] = []
    if path.is_file():
        existing_lines = path.read_text(encoding="utf-8").splitlines()

    current = parse_env_file(path)
    for key, val in updates.items():
        if val is None:
            current.pop(key, None)
        else:
            current[key] = val

    seen_keys: set[str] = set()
    new_lines: list[str] = []
    for line in existing_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue
        m = _ENV_LINE.match(stripped)
        if not m:
            new_lines.append(line)
            continue
        key = m.group(1)
        if key in updates:
            if updates[key] is not None:
                new_lines.append(f"{key}={format_env_value(updates[key])}")
            seen_keys.add(key)
        else:
            new_lines.append(line)
            seen_keys.add(key)

    for key, val in updates.items():
        if val is not None and key not in seen_keys:
            new_lines.append(f"{key}={format_env_value(val)}")

    if not new_lines and create:
        new_lines = ["# Generated by setup_wizard.py"]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
